export const menu = [
    {
        items: [{ routerLink: '/home', label: 'Install' }],
    },
    {
        groupName: 'Components',
        items: [
            { routerLink: '/component/block', label: 'Block' },
            { routerLink: '/component/color-picker', label: 'Color picker' },
            { routerLink: '/component/context-menu', label: 'Context menu' },
            { routerLink: '/component/contrib-calendar', label: 'Contrib calendar', status: 'new' },
            { routerLink: '/component/dialog', label: 'Dialog' },
            { routerLink: '/component/info-messages', label: 'Info-messages' },
            { routerLink: '/component/input', label: 'Inputs', status: 'update' },
            { routerLink: '/component/light-dark', label: 'Light-dark' },
            { routerLink: '/component/loader', label: 'Loader' },
            { routerLink: '/component/loader-block', label: 'Loader-block' },
            { routerLink: '/component/message', label: 'Message', status: 'new' },
            { routerLink: '/component/paginate', label: 'Paginate' },
            { routerLink: '/component/progress', label: 'Progress' },
            { routerLink: '/component/spinner', label: 'Spinner' },
            { routerLink: '/component/table', label: 'Table' },
            { routerLink: '/component/tabs', label: 'Tabs' },
            { routerLink: '/component/walkthrough', label: 'Walkthrough' },
        ],
    },
    {
        groupName: 'Directives',
        items: [
            { routerLink: '/directive/click-enter', label: 'Click Enter' },
            { routerLink: '/directive/click-outside', label: 'Click Outside' },
            { routerLink: '/directive/limit-focus', label: 'Limit-focus' },
            { routerLink: '/directive/ng-init', label: 'ngInit' },
            { routerLink: '/directive/ng-model-change-debounced', label: 'ngModelChange<br />debounced' },
            { routerLink: '/directive/sortable', label: 'Sortable ' },
            { routerLink: '/directive/stop-propagation', label: 'Stop Propagation' },
            { routerLink: '/directive/tooltip', label: 'Tooltip ' },
            { routerLink: '/directive/textarea-autosize', label: 'Textarea autosize' },
        ],
    },
    {
        groupName: 'Pipes',
        items: [
            { routerLink: '/pipe/array-filter', label: 'arrayFilter', status: 'new' },
            { routerLink: '/pipe/class-list', label: 'classList' },
            { routerLink: '/pipe/file-size', label: 'fileSize' },
            { routerLink: '/pipe/math', label: 'math' },
            { routerLink: '/pipe/num-format', label: 'numFormat' },
            { routerLink: '/pipe/repeat-for', label: 'repeatFor' },
            { routerLink: '/pipe/str-replace', label: 'strReplace', status: 'new' },
        ],
    },
    {
        groupName: 'Services',
        items: [{ routerLink: '/service/cache', label: 'Cache', status: 'new' }],
    },
    {
        groupName: 'Utils',
        items: [
            { routerLink: '/utils/array', label: 'Array', status: 'new' },
            { routerLink: '/utils/clipboard', label: 'Clipboard' },
            { routerLink: '/utils/coercion', label: 'Coercion' },
            { routerLink: '/utils/cookies', label: 'Cookies' },
            { routerLink: '/utils/css', label: 'CSS', status: 'new' },
            { routerLink: '/utils/date', label: 'Date' },
            { routerLink: '/utils/dom', label: 'DOM' },
            { routerLink: '/utils/email', label: 'Email' },
            { routerLink: '/utils/enum', label: 'Enum', status: 'new' },
            { routerLink: '/utils/file', label: 'File' },
            { routerLink: '/utils/json', label: 'Json' },
            { routerLink: '/utils/number', label: 'Number' },
            { routerLink: '/utils/object', label: 'Object' },
            { routerLink: '/utils/text', label: 'Text' },
            { routerLink: '/utils/subscriptions', label: 'Subscriptions' },
            { routerLink: '/utils/other', label: 'Other', status: 'new' },
        ],
    },
    {
        groupName: 'Styles',
        items: [
            { routerLink: '/style/buttons-links', label: 'Buttons & Links' },
            { routerLink: '/style/icons', label: 'Icons' },
            { routerLink: '/style/inputs', label: 'Inputs' },
            { routerLink: '/style/grid', label: 'Grid' },
            { routerLink: '/style/palette', label: 'Palette' },
        ],
    },
];
