import { ChangeDetectionStrategy, Component } from '@angular/core';

import { Highlight } from 'ngx-highlightjs';

@Component({
    selector: 'demo-icons',
    templateUrl: './demo-icons.component.html',
    styleUrl: './demo-icons.component.scss',
    changeDetection: ChangeDetectionStrategy.Eager,
    imports: [Highlight],
})
export class DemoIconsComponent {
    listIcons = [
        'icon-add',
        'icon-admin',
        'icon-arrow-down',
        'icon-arrow-down-2',
        'icon-arrow-left-2',
        'icon-arrow-right-2',
        'icon-arrow-up-2',
        'icon-background-color',
        'icon-banned',
        'icon-bookmark',
        'icon-browser',
        'icon-calendar',
        'icon-clone',
        'icon-deleted',
        'icon-dots-horizontal',
        'icon-dots-vertical',
        'icon-down',
        'icon-edit',
        'icon-edit-2',
        'icon-enlarge',
        'icon-expand',
        'icon-eye-close',
        'icon-eye-open',
        'icon-fullscreen',
        'icon-group',
        'icon-home',
        'icon-info',
        'icon-left',
        'icon-licenses',
        'icon-login',
        'icon-logout',
        'icon-minimize',
        'icon-minimize-2',
        'icon-minus',
        'icon-mode-axis',
        'icon-mode-column',
        'icon-mode-grid',
        'icon-mode-iceberg',
        'icon-mode-table',
        'icon-mode-teams',
        'icon-mode-tierlist',
        'icon-moderator',
        'icon-moon',
        'icon-not-verified',
        'icon-over',
        'icon-params',
        'icon-power',
        'icon-private',
        'icon-private-search',
        'icon-profile',
        'icon-public',
        'icon-public-search',
        'icon-reduce',
        'icon-remove',
        'icon-right',
        'icon-save-server',
        'icon-search',
        'icon-server',
        'icon-share',
        'icon-signup',
        'icon-sun',
        'icon-text-color',
        'icon-tile',
        'icon-under',
        'icon-up',
        'icon-user',
        'icon-validated',
        'icon-validated-A1',
        'icon-validated-A2',
        'icon-validated-A3',
        'icon-validated-B1',
        'icon-validated-B2',
        'icon-validated-B3',
        'icon-validated-C1',
        'icon-validated-C2',
        'icon-validated-C3',
        'icon-validated-D1',
        'icon-validated-D2',
        'icon-validated-D3',
        'icon-validated-E1',
        'icon-validated-E2',
        'icon-validated-E3',
        'icon-windows',
    ];

    selectedIcon: string | undefined;
    selectedIconCode: string | undefined;

    select(icon: string) {
        this.selectedIcon = icon;
        this.selectedIconCode = `<span class="${icon}"></span>`;
    }
}
